image: hub.realmanual.ru/images/docker
variables:
  DOCKER_BASEIMAGE: postgres:16-alpine
  DOCKER_MAINTAINER: vasyakrg@gmail.com
  DOCKER_NO_BRANCH_TAG: 1
  DOCKER_TAG_AS_LATEST: 1
  BUILD_SCRIPT: ci/build.sh
  GIT_SUBMODULE_STRATEGY: none

build:
  script:
    - export VERSION=$(cat VERSION)
    - chmod +x "${BUILD_SCRIPT}" && "./${BUILD_SCRIPT}"
